# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel

cache: packages

r_packages:
  - covr

addons:
  apt:
    update: true

sudo: false

script: 
  - |
    R CMD build .
    R CMD check ECOSolveR*tar.gz
    
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
